# Bag Of Words

In [16]:
import numpy as np 
import pandas as pd 

In [3]:
df = pd.DataFrame({'Text':['people watch movie','movie watch movie','people write comment','people love movie'], "output":[1,1,0,0]})

In [4]:
df

Text  output
0    people watch movie       1
1     movie watch movie       1
2  people write comment       0
3     people love movie       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [8]:
bow = cv.fit_transform(df['Text'])

In [10]:
print(cv.vocabulary_)

{'people': 3, 'watch': 4, 'movie': 2, 'write': 5, 'comment': 0, 'love': 1}


In [11]:
print(bow[0].toarray())

[[0 0 1 1 1 0]]


In [12]:
print(bow[1].toarray())

[[0 0 2 0 1 0]]


In [15]:
cv.transform(['people watch movie and like the movie']).toarray()

array([[0, 0, 2, 1, 1, 0]], dtype=int64)

# N - Grams

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [52]:
bow = cv.fit_transform(df['Text'])

In [53]:
print(len(cv.vocabulary_))

17


In [54]:
print
(cv.vocabulary_)

{'people': 6,
 'watch': 13,
 'movie': 3,
 'people watch': 9,
 'watch movie': 14,
 'people watch movie': 10,
 'movie watch': 4,
 'movie watch movie': 5,
 'write': 15,
 'comment': 0,
 'people write': 11,
 'write comment': 16,
 'people write comment': 12,
 'love': 1,
 'people love': 7,
 'love movie': 2,
 'people love movie': 8}

In [55]:
print(bow[0].toarray())

[[0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0]]


In [56]:
print(bow[1].toarray())

[[0 0 0 2 1 1 0 0 0 0 0 0 0 1 1 0 0]]


# TF - IDF

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['Text'])

In [67]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.91629073 1.22314355 1.22314355 1.51082562 1.91629073]
['comment' 'love' 'movie' 'people' 'watch' 'write']
